apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardano-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cardano
  persistentVolumeReclaimPolicy: Retain
