apiVersion: v1
kind: Service
metadata:
  name: cardano-db-sync
  labels:
    app: cardano-db-sync
spec:
  type: ClusterIP
  selector:
    app: cardano-db-sync
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080