# config/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-config
  namespace: cardano
data:
  config.json: |
    {
      "TraceBlockFetchDecisions": true,
      "TraceChainDb": true,
      "Logging": true,
      "SocketPath": "/ipc/node.socket"
    }
  topology.json: |
    {
      "Producers": [
        { "addr": "relays-new.cardano-mainnet.iohk.io",
          "port": 3001,
          "valency": 2
        }
      ]
    }