apiVersion: v1
kind: Service
metadata:
  name: cardano-service
  namespace: cardano
spec:
  selector:
    app: cardano-node
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP