apiVersion: v1
kind: PersistentVolume
metadata:
  name: tex-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/tex-node-operator
