apiVersion: v1
kind: Service
metadata:
  name: cardano-node
spec:
  type: LoadBalancer
  selector:
    app: cardano-node
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30010
