apiVersion: apps/v1
kind: Deployment
metadata:
  name: minswap-syncer
  namespace: cardano
  labels:
    app: minswap-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minswap-syncer
  template:
    metadata:
      labels:
        app: minswap-syncer
    spec:
      containers:
      - name: minswap-syncer
        image: ghcr.io/minswap/syncer:latest 
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: minswap-syncer-secret
              key: DATABASE_URL
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
        volumeMounts:
        - name: node-ipc
          mountPath: /ipc
      volumes:
      - name: node-ipc
        hostPath:
          path: /var/cardano/ipc
          type: Directory